/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ArchitectureLayer { 'title' : string, 'description' : string }
export type ContentType = { 'roadmap' : null } |
  { 'resource' : null } |
  { 'whitePaper' : null } |
  { 'tokenomics' : null } |
  { 'web2Web3' : null } |
  { 'projects' : null } |
  { 'homepage' : null } |
  { 'signup' : null } |
  { 'iomHybridPopup' : null } |
  { 'tmuIresPopup' : null };
export interface Guide { 'title' : string, 'description' : string }
export interface Project {
  'url' : string,
  'projectName' : string,
  'projectType' : ProjectType,
  'additionalButtons' : [] | [Array<string>],
  'projectDescription' : string,
  'category' : string,
  'imageId' : [] | [string],
}
export type ProjectType = { 'learnMore' : null } |
  { 'website' : null } |
  { 'multiButton' : null };
export interface PurchaseSummary {
  'fee' : bigint,
  'total' : bigint,
  'price' : bigint,
  'amount' : bigint,
}
export interface Resource { 'title' : string, 'filePath' : string }
export interface ResourcePageContent {
  'architectureLayers' : Array<ArchitectureLayer>,
  'resources' : Array<Resource>,
  'guides' : Array<Guide>,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TmuIresPopupContent {
  'title' : string,
  'documentationLink' : string,
  'description' : string,
  'videoLink' : string,
  'additionalLinks' : string,
}
export interface TokenPurchaseValidation {
  'sanitizedAmount' : bigint,
  'errorMessage' : [] | [string],
  'isValid' : boolean,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'createdAt' : Time,
  'fullName' : string,
  'walletAddress' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculatePurchaseSummary' : ActorMethod<[bigint], PurchaseSummary>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContent' : ActorMethod<[ContentType], string>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getResourcePageContent' : ActorMethod<[], ResourcePageContent>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTmuIresPopupContent' : ActorMethod<[], TmuIresPopupContent>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveSocialEdificationImage' : ActorMethod<[string], undefined>,
  'searchUserProfiles' : ActorMethod<[string], Array<UserProfile>>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'validateTokenAmount' : ActorMethod<[bigint], TokenPurchaseValidation>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];