/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PurchaseSummary = IDL.Record({
  'fee' : IDL.Nat,
  'total' : IDL.Nat,
  'price' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'createdAt' : Time,
  'fullName' : IDL.Text,
  'walletAddress' : IDL.Text,
  'email' : IDL.Text,
});
export const ContentType = IDL.Variant({
  'roadmap' : IDL.Null,
  'resource' : IDL.Null,
  'whitePaper' : IDL.Null,
  'tokenomics' : IDL.Null,
  'web2Web3' : IDL.Null,
  'projects' : IDL.Null,
  'homepage' : IDL.Null,
  'signup' : IDL.Null,
  'iomHybridPopup' : IDL.Null,
  'tmuIresPopup' : IDL.Null,
});
export const ProjectType = IDL.Variant({
  'learnMore' : IDL.Null,
  'website' : IDL.Null,
  'multiButton' : IDL.Null,
});
export const Project = IDL.Record({
  'url' : IDL.Text,
  'projectName' : IDL.Text,
  'projectType' : ProjectType,
  'additionalButtons' : IDL.Opt(IDL.Vec(IDL.Text)),
  'projectDescription' : IDL.Text,
  'category' : IDL.Text,
  'imageId' : IDL.Opt(IDL.Text),
});
export const ArchitectureLayer = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const Resource = IDL.Record({
  'title' : IDL.Text,
  'filePath' : IDL.Text,
});
export const Guide = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const ResourcePageContent = IDL.Record({
  'architectureLayers' : IDL.Vec(ArchitectureLayer),
  'resources' : IDL.Vec(Resource),
  'guides' : IDL.Vec(Guide),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const TmuIresPopupContent = IDL.Record({
  'title' : IDL.Text,
  'documentationLink' : IDL.Text,
  'description' : IDL.Text,
  'videoLink' : IDL.Text,
  'additionalLinks' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TokenPurchaseValidation = IDL.Record({
  'sanitizedAmount' : IDL.Nat,
  'errorMessage' : IDL.Opt(IDL.Text),
  'isValid' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculatePurchaseSummary' : IDL.Func(
      [IDL.Int],
      [PurchaseSummary],
      ['query'],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContent' : IDL.Func([ContentType], [IDL.Text], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getResourcePageContent' : IDL.Func([], [ResourcePageContent], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTmuIresPopupContent' : IDL.Func([], [TmuIresPopupContent], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveSocialEdificationImage' : IDL.Func([IDL.Text], [], []),
  'searchUserProfiles' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'validateTokenAmount' : IDL.Func(
      [IDL.Int],
      [TokenPurchaseValidation],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PurchaseSummary = IDL.Record({
    'fee' : IDL.Nat,
    'total' : IDL.Nat,
    'price' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'createdAt' : Time,
    'fullName' : IDL.Text,
    'walletAddress' : IDL.Text,
    'email' : IDL.Text,
  });
  const ContentType = IDL.Variant({
    'roadmap' : IDL.Null,
    'resource' : IDL.Null,
    'whitePaper' : IDL.Null,
    'tokenomics' : IDL.Null,
    'web2Web3' : IDL.Null,
    'projects' : IDL.Null,
    'homepage' : IDL.Null,
    'signup' : IDL.Null,
    'iomHybridPopup' : IDL.Null,
    'tmuIresPopup' : IDL.Null,
  });
  const ProjectType = IDL.Variant({
    'learnMore' : IDL.Null,
    'website' : IDL.Null,
    'multiButton' : IDL.Null,
  });
  const Project = IDL.Record({
    'url' : IDL.Text,
    'projectName' : IDL.Text,
    'projectType' : ProjectType,
    'additionalButtons' : IDL.Opt(IDL.Vec(IDL.Text)),
    'projectDescription' : IDL.Text,
    'category' : IDL.Text,
    'imageId' : IDL.Opt(IDL.Text),
  });
  const ArchitectureLayer = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const Resource = IDL.Record({ 'title' : IDL.Text, 'filePath' : IDL.Text });
  const Guide = IDL.Record({ 'title' : IDL.Text, 'description' : IDL.Text });
  const ResourcePageContent = IDL.Record({
    'architectureLayers' : IDL.Vec(ArchitectureLayer),
    'resources' : IDL.Vec(Resource),
    'guides' : IDL.Vec(Guide),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const TmuIresPopupContent = IDL.Record({
    'title' : IDL.Text,
    'documentationLink' : IDL.Text,
    'description' : IDL.Text,
    'videoLink' : IDL.Text,
    'additionalLinks' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TokenPurchaseValidation = IDL.Record({
    'sanitizedAmount' : IDL.Nat,
    'errorMessage' : IDL.Opt(IDL.Text),
    'isValid' : IDL.Bool,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculatePurchaseSummary' : IDL.Func(
        [IDL.Int],
        [PurchaseSummary],
        ['query'],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContent' : IDL.Func([ContentType], [IDL.Text], ['query']),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getResourcePageContent' : IDL.Func([], [ResourcePageContent], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTmuIresPopupContent' : IDL.Func([], [TmuIresPopupContent], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveSocialEdificationImage' : IDL.Func([IDL.Text], [], []),
    'searchUserProfiles' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'validateTokenAmount' : IDL.Func(
        [IDL.Int],
        [TokenPurchaseValidation],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };